### ISSUE TITLE
Home icon en colmena lanza una excepción

### ISSUE THREAD

**Issue by edzlo** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#86]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.davidmiguel.gobees.mock, PID: 23858
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.davidmiguel.gobees.mock/com.davidmiguel.gobees.apiary.ApiaryActivity}: java.lang.IllegalArgumentException: No apiary id passed!
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
                      at android.app.ActivityThread.access$900(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
                      at android.os.Handler.dispatchMessage(Handler.java)
                      at android.os.Looper.loop(Looper.java)
                      at android.app.ActivityThread.main(ActivityThread.java)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
                   Caused by: java.lang.IllegalArgumentException: No apiary id passed!
                      at com.davidmiguel.gobees.apiary.ApiaryActivity.onCreate(ApiaryActivity.java:60)
                      at android.app.Activity.performCreate(Activity.java)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java) 
                      at android.app.ActivityThread.access$900(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java) 
                      at android.os.Handler.dispatchMessage(Handler.java) 
                      at android.os.Looper.loop(Looper.java) 
                      at android.app.ActivityThread.main(ActivityThread.java) 
                      at java.lang.reflect.Method.invoke(Native Method)

Solución:

- http://stackoverflow.com/a/17342137/6305235
- https://speakerdeck.com/jgilfelt/this-way-up-implementing-effective-navigation-on-android
- http://stackoverflow.com/questions/25773928/setting-launchmode-singletask-vs-setting-activity-launchmode-singletop

**Comment by edzlo** [comment]
Resuelto
